name: GitHub Actions Demo
# Gives the workflow name the same as the project name
run-name: ${{ github.actor }} is building ${{ github.event.repository.name }} ğŸš€
on: [push]
jobs:
  Build-OS4-Shared-Library:
    runs-on: ubuntu-latest
    container:
      image: amigadev/crosstools:ppc-amigaos
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to build your project on the runner."
      - name: List files in the repository
        run: |
          pwd
          ls .
          echo ${{ github.workspace }}
      - name: Builds the OS4 shared library ğŸ“š and uploads it as an artifact
        id: os4_shared_library
        run: |
          cmake .
          echo "ğŸ“ CMake has been run successfully."
          make -f Makefile
          echo "ğŸ›  Make did its job."
      - name: ğŸ—º preparing the artifact
        run: |
          echo "ğŸ“¦ The artifact is ready."
      - name: Upload the Artifact ğŸº
        uses: actions/upload-artifact@v3
        with:
          name: uuid.library_os4
          path: uuid.library
      - run: echo "ğŸ This job's status is ${{ job.status }}."

# on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
# jobs:
#  build_ppc:
#    runs-on: ubuntu-latest
#    container:
#      image: amigadev/crosstools:ppc-amigaos
#    name: os4
#    steps:
#      - uses: actions/checkout@v2
#      - name: buildos4
#        id: buildos4
#        run: |
#          cd ./uuid_files
#          make -f Makefile
#      - uses: actions/upload-artifact@v1
#        with:
#          name: uuid.library
#          path: uuid_files/uuid.library
#  build_68k:
#    runs-on: ubuntu-latest
#    container:
#      image: amigadev/crosstools:m68k-amigaos
#    name: os3
#    steps:
#      - uses: actions/checkout@v2
#      - name: buildos3
#        id: buildos3
#        run: make -f src/Makefile.os3

