name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

# on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
# jobs:
#  build_ppc:
#    runs-on: ubuntu-latest
#    container:
#      image: amigadev/crosstools:ppc-amigaos
#    name: os4
#    steps:
#      - uses: actions/checkout@v2
#      - name: buildos4
#        id: buildos4
#        run: |
#          cd ./uuid_files
#          make -f Makefile
#      - uses: actions/upload-artifact@v1
#        with:
#          name: uuid.library
#          path: uuid_files/uuid.library
#  build_68k:
#    runs-on: ubuntu-latest
#    container:
#      image: amigadev/crosstools:m68k-amigaos
#    name: os3
#    steps:
#      - uses: actions/checkout@v2
#      - name: buildos3
#        id: buildos3
#        run: make -f src/Makefile.os3

